# Generated by Django 3.2.10 on 2022-02-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
