# Generated by Django 3.2.10 on 2022-01-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentdefault',
            name='description',
        ),
    ]
