# Generated by Django 3.2.10 on 2022-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_projectformdefault_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectformdefault',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
