# Generated by Django 3.2.10 on 2022-01-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectformdefault_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectformdefault',
            name='team_type',
            field=models.ManyToManyField(blank=True, to='project.TeamType'),
        ),
    ]
