# Generated by Django 3.2.10 on 2022-01-11 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_alter_projectformdefault_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='to_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
