# Generated by Django 3.2.10 on 2022-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectform_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
