# Generated by Django 3.2.10 on 2022-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectform_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
