# Generated by Django 3.2.10 on 2022-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
