# Generated by Django 3.2.10 on 2022-01-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_projectform_cloned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectform',
            old_name='cloned',
            new_name='clone',
        ),
    ]
