# Generated by Django 3.2.10 on 2022-01-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_cloned_projectform_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdefault',
            name='form_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_default_document', to='project.projectformdefault'),
        ),
    ]
