# Generated by Django 3.2.10 on 2022-01-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_documentdefault_form_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdefault',
            name='form_default',
        ),
    ]
