# Generated by Django 3.2.10 on 2022-01-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0015_auto_20220128_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
