# Generated by Django 3.2.10 on 2022-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20220128_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
