# Generated by Django 3.2.10 on 2022-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_invite_invite_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='document',
        ),
        migrations.AddField(
            model_name='invite',
            name='meet',
            field=models.ManyToManyField(blank=True, to='project.Meet'),
        ),
    ]
