# Generated by Django 3.2.10 on 2022-02-01 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0019_auto_20220129_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
