# Generated by Django 3.2.10 on 2022-01-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=50),
        ),
    ]
