# Generated by Django 3.2.10 on 2022-01-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id', '-created_at')},
        ),
    ]
